# Generated by Django 4.2.1 on 2023-06-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0015_gallery_detected_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
