# Generated by Django 4.2.1 on 2023-06-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0016_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'get_latest_by': 'id'},
        ),
        migrations.RemoveField(
            model_name='camcard',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='camcard',
            name='timestamp',
        ),
    ]
