# Generated by Django 4.2.1 on 2023-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_tray_detector', '0017_alter_gallery_options_remove_camcard_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type_tray',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
