# Generated by Django 4.2.1 on 2023-06-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0014_alter_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip_camera', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
