# Generated by Django 4.2.1 on 2023-06-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_detector', '0015_ipcamera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipcamera',
            options={'get_latest_by': 'id'},
        ),
    ]
