# Generated by Django 4.2.1 on 2023-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_can_detector', '0004_alter_camcard_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camcard',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='camcard',
            name='timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
