# Generated by Django 4.2.1 on 2023-06-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash_can_detector', '0005_alter_camcard_quantity_alter_camcard_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
