# Generated by Django 4.2.1 on 2023-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_can_detector', '0008_remove_camcard_quantity_remove_camcard_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='quantity',
            new_name='capacity',
        ),
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_camera',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
